### ISSUE TITLE
Deprecated - critical bugs

### ISSUE THREAD

**Issue by sfmc** [XpsToPdf/XpsToPdf#1]
Hi, 

Is there more details on why NuGet displays the following error: "This package has been deprecated as it has critical bugs."

Is this project under development?

Thank you!

**Comment by Orace** [comment]
Please roll back to [v1.0.0](https://www.nuget.org/packages/XpsToPdf/1.0.0)

The project is not under development, as it doesn't need new features yet.

**Comment by Orace** [comment]
Since [v1.0.2 is released](https://www.nuget.org/packages/XpsToPdf/1.0.2) this issue can be closed.
