### ISSUE TITLE
PdfEncoders.WinAnsiEncoding getter crash on .net Core.

### ISSUE THREAD

**Issue by b-mi** [XpsToPdf/XpsToPdf#2]
Other - online - converters convert the same xps file to pdf file correctly.

**Comment by Orace** [comment]
cool story bro.

**Comment by b-mi** [comment]
Ok, try to convert this xps by code:

  PdfSharp.Xps.XpsConverter.Convert(xpsFile, pdfFile, 0);

[tmp60d982b_0A_14120.zip](https://github.com/XpsToPdf/XpsToPdf/files/8609340/tmp60d982b_0A_14120.zip)

Thank you.

**Comment by Orace** [comment]
I'm currently baking a strawberry pie, I don't have time to set everything up right now.
I understood that it does not work with the xps file that you provide.
You can at least provide the pdf too and point where there is a problem if needed (I guess it's obvious).

**Comment by b-mi** [comment]
I don't think you can help. Continue to baking pie.

**Comment by Orace** [comment]
If you want some help to resolve a problem, you may have to learn how to describe your problem.  
When I try to convert the xps file you provided, I got a `System.NullReferenceException: 'Object reference not set to an instance of an object.'` in `XpsDocument.GetPartAsXmlReader`.  
Is that the issue?
And don't try to replay [Gilfoyle vs HR](https://www.youtube.com/watch?v=HkFztAgK-8U) with me. I will help you anyway.

**Comment by Orace** [comment]
Looks like an encoding issue. The file use code page 1252. I'm able to generate a pdf using [this SO answer](https://stackoverflow.com/a/37870346/361177)

    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
    PdfSharp.Xps.XpsConverter.Convert(xpsFile, pdfFile, 0);

An other issue then is that the pdf only have one page.

**Comment by b-mi** [comment]
Thank you for your instruction.

I will summarize the data
1) The input xps file contains more than one page (in the attachment)
2) The output pdf file contains only the first page (in the attachment out.pdf) - THIS is the problem
3) Conversion code used: PdfSharp.Xps.XpsConverter.Convert (pdfXpsDoc, pdfFile3, 0);
4) There will be no exception during the transfer (code page 1252 is present)
5) If an exception occurs, it is probably the internal matter is PdfSharp.Xps.XpsConverter
6) The conversion of the same input xps file ends with the correct result in use:
- https://xpstopdf.com/
- https://online2pdf.com/convert-xps-to-pdf

Thank you for a possible solution.
[tmp60d982b_0A_14120.zip](https://example.com)

**Comment by Orace** [comment]
>     2. The output pdf file contains only the first page (in the attachment out.pdf) - THIS is the problem

Issue #3 as been open for this.

This issue will focus on the code page problem.

**Comment by Orace** [comment]
Fixed by #5 
Released in [1.0.2.0](https://www.nuget.org/packages/XpsToPdf/1.0.2).

**Comment by b-mi** [comment]
Thanks for the quick fix, it's okay now.
