### ISSUE TITLE
.NET 6.0

### ISSUE THREAD

**Issue by trdsolutions** [XpsToPdf/XpsToPdf#6]
Hello,

I experienced some issues, when using this library in a .NET 6.0 application.
While the XPS to PDF conversion with normal english characters still "works" without an expection, the converted PDF file, will not have visible text displayed there. You can still select the invisible text and, copy and paste it into a notepad and the text is as expected, but invisible in the PDF file.

Additionally, less common characters (i.e. "ĄĘŚĆŹŻ 诶必西-アメリ") will throw a NullReferenceException.

Both of these issues only occur, when the application is targeting .NET 6.0. With .NET 5.0 everything just works fine.

Do you want me to setup a example solution for being able to reproduce it or are the given information already enough?

**Comment by trdsolutions** [comment]
[XpsToPdfDemo.zip](https://github.com/XpsToPdf/XpsToPdf/files/8797678/XpsToPdfDemo.zip)

In the meanwhile I created a small solution, where the issue can be reproduced. (I think I forgot to reset the TFM to .NET6.0, but switching between these both makes the difference between working and not-working ;-)

**Comment by Orace** [comment]
It was an issue in `XpsDocument.GetPartAsBytes` in the way a stream was copied to a byte array.  
As specified in the **Remarks** section of [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0#system-io-stream-read(system-byte()-system-int32-system-int32)) of `stream.Read`: *An implementation is free to return fewer bytes than requested even if the end of the stream has not been reached.*

https://github.com/XpsToPdf/XpsToPdf/blob/800d929cb0576aa6af2db782e40917797cf51678/XpsToPdf/PdfSharp.Xps.XpsModel/XpsDocument.cs#L166-L173

**Comment by trdsolutions** [comment]
Wow, that was really quick, I haven't expected this! Thank you very much! I assume there will be an updated nuget package later this day?

**Comment by Orace** [comment]
Fix is available in [version 1.0.3](https://www.nuget.org/packages/XpsToPdf/1.0.3)  
Your assumption is correct 😉

**Comment by trdsolutions** [comment]
I tried it and it works, thank you so much for this great support!
