### ISSUE TITLE
Strong named assembly

### ISSUE THREAD

**Issue by tom42** [XpsToPdf/XpsToPdf#9]
Hello,

I need to integrate XpsToPdf into a software that has its assemblies strong named and which I cannot change, so I need XpsToPdf to be strong named too.

If I created a pull request, would you be willing to merge it, or is this something you'd rather not have?

Thanks&Regards
Thomas

**Comment by Orace** [comment]
Fixed by 9c68eb1, released in [v1.0.5.0](https://www.nuget.org/packages/XpsToPdf/1.0.5)
